# Mount Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Import Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.linear_model import Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

# Tag Along

In [3]:
df = pd.read_csv("/content/drive/MyDrive/HDSC Spring 2024/Stage B tag along/energydata_complete.csv")

In [4]:
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [6]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [7]:
y = np.asanyarray(df['T6'])
y = y.reshape(-1, 1)

In [8]:
x = np.asanyarray(df['T2'])
x = x.reshape(-1, 1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [10]:
lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = lin_model.predict(X_test)
y_pred

array([[ 2.15578912],
       [10.01116055],
       [ 1.87391554],
       ...,
       [ 4.24758774],
       [ 8.69822311],
       [ 4.9893603 ]])

In [12]:
rmse_value = np.sqrt(mean_squared_error(y_test, y_pred))
rounded_rmse = round(rmse_value, 3)
print("RMSE:", rounded_rmse)

RMSE: 3.63


In [13]:
df.drop(columns=['date', 'lights'], inplace=True)

In [28]:
x = df.drop(['Appliances'],axis=1)
y = df['Appliances']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [30]:
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)

In [31]:
model = LinearRegression()
model.fit(X_train_normalized, y_train)

LinearRegression()

In [32]:
predicted_values = model.predict(X_train_normalized)
predicted_values

array([ 49.97775425, 100.31632974,  40.12912536, ...,  59.47229745,
       103.23225103,  88.1415215 ])

In [34]:
mae = mean_absolute_error(y_train, predicted_values)
round(mae, 3)

53.742

In [35]:
rmse = np.sqrt(mean_squared_error(y_train, predicted_values))
round(rmse, 3)

95.216

In [36]:
predicted_values_test = model.predict(X_test_normalized)
mae = mean_absolute_error(y_test, predicted_values_test)
round(mae, 3)

53.643

In [39]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values_test))
round(rmse, 3)

93.64

In [40]:
ridge_model = Ridge()
ridge_model.fit(X_train_normalized, y_train)

Ridge()

In [44]:
predicted_values_ridge = ridge_model.predict(X_test_normalized)

In [45]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values_ridge))
round(rmse, 3)

93.709

In [47]:
lasso = Lasso()
lasso.fit(X_train, y_train)

Lasso()

In [48]:
predicted_values_lasso = lasso.predict(X_test)
predicted_values_lasso

array([ 44.90097769, 262.85190481,  50.99187535, ...,  84.13983747,
       115.96268821,  77.00102843])

In [49]:
def get_weights_df(model, data, col_name):
    weights = pd.Series(model.coef_, data.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [50]:
lasso_weights = get_weights_df(lasso, X_train, 'Lasso_Model_weight')
lasso_weights

Features  Lasso_Model_weight
0            T9       -1.639155e+01
1            T2       -1.075746e+01
2          RH_2       -1.014653e+01
3          RH_8       -5.457679e+00
4         T_out       -3.696347e+00
5          RH_7       -1.724493e+00
6            T5       -1.589092e+00
7          RH_9       -1.549707e+00
8        RH_out       -1.821188e-02
9            T1       -0.000000e+00
10    Tdewpoint        0.000000e+00
11           T7       -0.000000e+00
12         RH_4        0.000000e+00
13           T4       -0.000000e+00
14          rv2        1.625869e-17
15          rv1        2.353054e-02
16  Press_mm_hg        8.695188e-02
17   Visibility        1.772175e-01
18         RH_5        2.509821e-01
19         RH_6        3.035808e-01
20    Windspeed        2.191789e+00
21         RH_3        3.657718e+00
22           T6        4.817203e+00
23           T8        6.597932e+00
24         RH_1        1.483957e+01
25           T3        2.121530e+01

In [51]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values_lasso))
round(rmse, 3)

93.892